version: '3.8'

services:
  mongodb:
    image: mongo:5.0.22
    container_name: mongodb-beadando
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./volumes/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=foreignWork
    ports:
      - 27017:27017
    networks:
      - vizsga-network

  mongo-express:
    image: mongo-express:1.0.0-20
    container_name: mongo-express-beadando
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_AUTH_DATABASE=foreignWork
      - ME_CONFIG_MONGODB_AUTH_USERNAME=manager
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=manager
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    ports:
      - 8888:8081
    networks:
      - vizsga-network

networks:
  vizsga-network:
    name: 'vizsga-network'
